server:
  port: 9001
  servlet:
    context-path: /v1/api

# SPRING DATA / DB
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=yield_01
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: on